language: java
jdk:
  - oraclejdk8
sudo: false # faster builds

before_install:
  - mysql < db/schema.sql
  - mysql -e "USE mysql; UPDATE user SET password=PASSWORD('root') WHERE user='root'; FLUSH PRIVILEGES;"
script: mvn test

after_success:
  - bash <(curl -s https://codecov.io/bash)