language: java
jdk:
  - oraclejdk8

before_install:
  - mysql < db/schema.sql
  - mysql -e "USE mysql; UPDATE user SET password=PASSWORD('root') WHERE user='root'; FLUSH PRIVILEGES;"
  - wget https://github.com/HandyMenny/coveralls-maven-plugin/releases/download/v4.4.0-CUSTOM/coveralls-maven-plugin-4.4.0-SNAPSHOT.jar
  - mvn org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file  -Dfile=coveralls-maven-plugin-4.4.0-SNAPSHOT.jar
script: mvn test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn coveralls:report
  - printf "\n\n\033[1m\033[33mTest output\n\n\033[0m"
  - for i in $(find target/surefire-reports/*txt ); do printf "\033[1m\033[36m\nFile: "$i"\n\033[0m" && cat $i -n; done
